### ISSUE TITLE
Subscriber flips not cleaned up properly when app stops

### ISSUE THREAD

**Issue by stonier** [robotics-in-concert/rocon_app_platform#18]
Happens either with app manager dying, or stop app being called.

Probably because the node doesn't get time to receive the update() call from the remote master.

```
Exception in thread Thread-6:
Traceback (most recent call last):
  File "/usr/lib/python2.7/threading.py", line 551, in __bootstrap_inner
    self.run()
  File "/opt/multimaster/rocon_multimaster/rocon_gateway/src/rocon_gateway/hub_api.py", line 126, in run
    self._remote_gateway_request_callbacks['unflip'](utils.get_rule_from_list(contents), source)
  File "/opt/multimaster/rocon_multimaster/rocon_gateway/src/rocon_gateway/gateway_sync.py", line 497, in process_remote_gateway_unflip_request
    self.master.unregister(existing_registration)
  File "/opt/multimaster/rocon_multimaster/rocon_gateway/src/rocon_gateway/master_api.py", line 117, in unregister
    xmlrpcapi(registration.connection.xmlrpc_uri).publisherUpdate('/master', registration.connection.rule.name, [])
  File "/usr/lib/python2.7/xmlrpclib.py", line 1224, in __call__
    return self.__send(self.__name, args)
  File "/usr/lib/python2.7/xmlrpclib.py", line 1578, in __request
    verbose=self.__verbose
  File "/usr/lib/python2.7/xmlrpclib.py", line 1264, in request
    return self.single_request(host, handler, request_body, verbose)
  File "/usr/lib/python2.7/xmlrpclib.py", line 1292, in single_request
    self.send_content(h, request_body)
  File "/usr/lib/python2.7/xmlrpclib.py", line 1439, in send_content
    connection.endheaders(request_body)
  File "/usr/lib/python2.7/httplib.py", line 954, in endheaders
    self._send_output(message_body)
  File "/usr/lib/python2.7/httplib.py", line 814, in _send_output
    self.send(msg)
  File "/usr/lib/python2.7/httplib.py", line 776, in send
    self.connect()
  File "/usr/lib/python2.7/httplib.py", line 757, in connect
    self.timeout, self.source_address)
  File "/usr/lib/python2.7/socket.py", line 571, in create_connection
    raise err
error: [Errno 111] Connection refused
```

**Comment by stonier** [comment]
Partially fixed by https://github.com/robotics-in-concert/rocon_multimaster/commit/ce0fe5e75a939163ba15a297640d315df6594bc8

It now stops ok, but app manager could use better unflip handling when stopping an app. That will have to wait until https://github.com/robotics-in-concert/rocon_multimaster/issues/102 is implemented.

**Comment by jihoonl** [comment]
https://github.com/robotics-in-concert/rocon_multimaster/issues/128
