### ISSUE TITLE
rapp_path not defined.

### ISSUE THREAD

**Issue by jihoonl** [robotics-in-concert/rocon_app_platform#203]
The recent pull request on rocon_app_utilities broke `rocon_app list` command.

```
jihoonl@whoola:~/research/ros/rocon/src/rocon_app_platform/rocon_app_utilities/src/rocon_app_utilities$ rocon_app list
Error: global name 'rapp_path' is not defined
Traceback (most recent call last):
  File "/home/jihoonl/research/ros/rocon/src/rocon_app_platform/rocon_app_utilities/src/rocon_app_utilities/rapp_cmd.py", line 193, in main
    _rapp_cmd_list(argv)
  File "/home/jihoonl/research/ros/rocon/src/rocon_app_platform/rocon_app_utilities/src/rocon_app_utilities/rapp_cmd.py", line 33, in _rapp_cmd_list
    indexer = RappIndexer()
  File "/home/jihoonl/research/ros/rocon/src/rocon_app_platform/rocon_app_utilities/src/rocon_app_utilities/indexer.py", line 33, in __init__
    self.update_index(package_whitelist, package_blacklist)
  File "/home/jihoonl/research/ros/rocon/src/rocon_app_platform/rocon_app_utilities/src/rocon_app_utilities/indexer.py", line 51, in update_index
    r.load_rapp_yaml_from_file(rapp_path)
NameError: global name 'rapp_path' is not defined
```

**Comment by jihoonl** [comment]
`rapp_path` and `package` are not defined in `update_index()` method

**Comment by bit-pirate** [comment]
Looking into this.

**Comment by bit-pirate** [comment]
Works for me now. Re-open, if the issues still exists.

**Comment by bit-pirate** [comment]
PS: I missed changing those names when merging Esteve's and Daniel's PRs.
