### ISSUE TITLE
Shutting down erroneously checking current rapp

### ISSUE THREAD

**Issue by stonier** [robotics-in-concert/rocon_app_platform#217]
When shutting down a simple turtle_concert, the clients are throwing up this traceback:

```
Traceback (most recent call last):
  File "/mnt/zaphod/ros/rocon/src/rocon_app_platform/rocon_app_manager/src/rocon_app_manager/rapp_manager.py", line 601, in _monitor_rapp
    self._process_stop_app()
  File "/mnt/zaphod/ros/rocon/src/rocon_app_platform/rocon_app_manager/src/rocon_app_manager/rapp_manager.py", line 578, in _process_stop_app
    if 'required_capabilities' in self._current_rapp.data:
AttributeError: 'NoneType' object has no attribute 'data'
[INFO] [WallTime: 1398607713.795569] Gateway : shutting down.
```

**Comment by stonier** [comment]
Seems to be happening `100%`.
