### ISSUE TITLE
rocon_app list --uri not working.

### ISSUE THREAD

**Issue by jihoonl** [robotics-in-concert/rocon_app_platform#255]
```
jihoonl@whoola:~/research/ros/turtlebot/src$ rocon_app list --uri rocon://pc
Error: 
Traceback (most recent call last):
  File "/home/jihoonl/research/ros/turtlebot/src/rocon_app_platform/rocon_app_utilities/src/rocon_app_utilities/rapp_cmd.py", line 304, in main
    _rapp_cmd_list(argv)
  File "/home/jihoonl/research/ros/turtlebot/src/rocon_app_platform/rocon_app_utilities/src/rocon_app_utilities/rapp_cmd.py", line 44, in _rapp_cmd_list
    index = get_index(uri)
  File "/home/jihoonl/research/ros/turtlebot/src/rocon_app_platform/rocon_app_utilities/src/rocon_app_utilities/rapp_repositories.py", line 177, in get_index
    return build_index(url, package_whitelist=package_whitelist, package_blacklist=package_blacklist)
  File "/home/jihoonl/research/ros/turtlebot/src/rocon_app_platform/rocon_app_utilities/src/rocon_app_utilities/rapp_repositories.py", line 129, in build_index
    assert isinstance(base_paths, list)
AssertionError
```

**Comment by jihoonl** [comment]
Well... I was confused with uri and compatibility... It works.

> rocon_app list --uri https://github.com/yujinrobot/kobuki/raw/rapp_index/kobuki_apps/rapps.index.tar.gz`
