### ISSUE TITLE
rapp_manager dies when it fails to load app_lists

### ISSUE THREAD

**Issue by jihoonl** [robotics-in-concert/rocon_app_platform#40]
If app_lists param get set as default value('') it crashes.

```
Traceback (most recent call last):
  File "/home/jihoonl/ros/rocon/src/rocon_app_platform/rocon_app_manager/scripts/rapp_manager.py", line 21, in <module>
    manager = rocon_app_manager.RappManager()
  File "/home/jihoonl/ros/rocon/src/rocon_app_platform/rocon_app_manager/src/rocon_app_manager/rapp_manager.py", line 56, in __init__
    self._get_pre_installed_app_list()  # It sets up an app directory and load installed app list from directory
  File "/home/jihoonl/ros/rocon/src/rocon_app_platform/rocon_app_manager/src/rocon_app_manager/rapp_manager.py", line 151, in _get_pre_installed_app_list
    app_list_file = RappListFile(filename)
  File "/home/jihoonl/ros/rocon/src/rocon_app_platform/rocon_app_manager/src/rocon_app_manager/rapp_list.py", line 50, in __init__
    self.update()
  File "/home/jihoonl/ros/rocon/src/rocon_app_platform/rocon_app_manager/src/rocon_app_manager/rapp_list.py", line 68, in update
    s = os.stat(self.filename)
OSError: [Errno 2] No such file or directory: '/home/jihoonl/ros/rocon/src/rocon_app_platform/rocon_apps/apps/rocon_rapps'
[app_manager-12] process has died [pid 22284, exit code 1, cmd /home/jihoonl/ros/rocon/src/rocon_app_platform/rocon_app_manager/scripts/rapp_manager.py app_manager/gateway_info:=gateway/gateway_info app_manager/flip:=gateway/flip __name:=app_manager __log:=/home/jihoonl/.ros/log/5fdf5032-aff0-11e2-b05a-20689df5aa4b/app_manager-12.log].
log file: /home/jihoonl/.ros/log/5fdf5032-aff0-11e2-b05a-20689df5aa4b/app_manager-12*.log
```

**Comment by stonier** [comment]
Just a warning?
